//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HopDong()
        {
            this.TaiLieux = new HashSet<TaiLieu>();
            this.ThanhToans = new HashSet<ThanhToan>();
        }
    
        public int IDHopDong { get; set; }
        public string MaHopDong { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> NguoiTao { get; set; }
        public Nullable<int> IDKhachHang { get; set; }
        public Nullable<int> IDLoaiHD { get; set; }
        public Nullable<byte> Active { get; set; }
        public Nullable<decimal> ChiPhi { get; set; }
        public Nullable<decimal> DaThanhToan { get; set; }
        public Nullable<System.DateTime> NgayKy { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> HanHD { get; set; }
        public Nullable<int> NguoiPhuTrach { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual LoaiHD LoaiHD { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaiLieu> TaiLieux { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThanhToan> ThanhToans { get; set; }
    }
}
